Window.SetBackgroundTopColor(0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor(0.0, 0.0, 0.0);

logo_image = Image("darkos.png");
logo_image = logo_image.Scale(180, 180);
logo_sprite = Sprite(logo_image);
logo_sprite.SetX(Window.GetWidth() / 2 - logo_image.GetWidth() / 2);
logo_sprite.SetY(Window.GetHeight() / 2 - logo_image.GetHeight() / 2 - 24);

tagline_image = Image.Text("CONTROL EVERYTHING", 0.0, 0.898, 1.0);
tagline_sprite = Sprite(tagline_image);
tagline_sprite.SetX(Window.GetWidth() / 2 - tagline_image.GetWidth() / 2);
tagline_sprite.SetY(Window.GetHeight() / 2 + 88);

fun refresh_callback() {
    progress = Plymouth.GetBootProgress();
    logo_sprite.SetOpacity(0.72 + progress * 0.28);
}

Plymouth.SetRefreshFunction(refresh_callback);
