# SPDX-License-Identifier: GPL-3.0-or-later
---
efiBootLoader: "grub"
kernelSearchPath: "/usr/lib/modules"
kernelName: "vmlinuz"
timeout: "10"
bootloaderEntryName: "DarkOS"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiMountDir: "/efi"
installEFIFallback: true
