# SPDX-License-Identifier: GPL-3.0-or-later
#
# Partitioning — guided layout for a clean DarkOS install.

---
defaultFileSystemType: ext4
defaultPartitionTable: gpt
drawNestedPartitions: false
alwaysShowPartitionLabels: true
enableLuks: true
efiMountPoint: "/efi"
