# SPDX-License-Identifier: GPL-3.0-or-later
---
services:
  - name: NetworkManager
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: seatd
    mandatory: true
  - name: pipewire
    mandatory: true
  - name: pipewire-pulse
    mandatory: true
  - name: darkos-grub-repair
    mandatory: true
