# Calamares settings for DarkOS
# Minimal configuration — expand as modules are built out
---
modules-search: [ /usr/lib/calamares/modules ]

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - luksbootkeyfile
    - luksopenswaphookcfg
    - plymouthcfg
    - bootloader
    - services-systemd
    - users
    - networkcfg
    - hwclock
    - umount
- show:
    - finished

branding: darkos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
