# Calamares settings for DarkOS
# Minimal configuration — expand as modules are built out
---
modules-search: [ /usr/lib/calamares/modules ]

sequence:
- branding:
    - welcome
- locale:
    - locale
    - keyboard
- locale:
    - timezone
- partition:
    - partition
- users:
    - users
- services:
    - services-systemd
- postcfg:
    - luksbootkeyfile
    - grubcfg
    - bootloader
- postcfg:
    - networkcfg
    - hwclock
- preinstall:
    - summary
- install:
    - umount
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - luksbootkeyfile
    - luksopenswaphookcfg
    - plymouthcfg
    - grubcfg
    - bootloader
    - services-systemd
    - users
    - cleanup
- postinstall:
    - hwclock
- finish:
    - finished

branding: darkos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
